services:
  - type: web
    name: roster-manager
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn roster_manager.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.0"
